@webapi_cshap_HostAddress = http://localhost:5186

GET {{webapi_cshap_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{webapi_cshap_HostAddress}}/api/Character
Content-Type: application/json

{
  "name": "Eduardo",
  "type": "Desenvolvedor Pleno"
}

